### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by janwerkhoven** [janwerkhoven/ember-interflux-website#21]
### Phase 1- Build current website in Ember + Rails

* [ ] 1. Build current website in Ember, launch on [staging.interflux.com](staging.interflux.com) (static content)
* [ ] 2. Get feedback from Interflux team
* [ ] 3. Build Rails API on [api.interflux.com](api.interflux.com)
* [ ] 4. Build Admin on [admin.interflux.com](admin.interflux.com)
* [ ] 5. Hook Ember app up to API (dynamic content)
* [ ] 5. Secure servers with HTTPS
* [ ] 6. Optimise Ember app for Google bots, test if pages can be fetched
* [ ] 7. Create XML sitemap for Google bots
* [ ] 8. Get feedback from Interflux team
* [ ] 9. Launch Ember website on www.interflux.com!
* [ ] 10. Park the Drupal website on [legacy.interflux.com](legacy.interflux.com) for reference

### Add product pages

* [ ] 3. Add product pages
